name: Lint, Build and Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v3

      - name: ğŸ› Setup Node
        if: github.event.action != 'closed'
        uses: actions/setup-node@v3
        with:
          node-version: 16.16
          cache: 'yarn'

      - name: âš™ï¸ Install
        if: github.event.action != 'closed'
        run: yarn

      - name: ğŸ¨ Lint JS
        if: github.event.action != 'closed'
        run: yarn lint:js

      - name: ğŸ¨ Lint CSS
        if: github.event.action != 'closed'
        run: yarn lint:css

      - name: ğŸ¨ Lint Format
        if: github.event.action != 'closed'
        run: yarn lint:format

      - name: ğŸ¨ Lint Types
        if: github.event.action != 'closed'
        run: yarn lint:types

      - name: ğŸ¯ Test
        if: github.event.action != 'closed'
        run: yarn test:unit

      - name: ğŸ›  Build (@/pr-preview/pr-${{ github.event.number }})
        if: github.event.action != 'closed'
        run: PUBLIC_PATH=/pr-preview/pr-${{ github.event.number }} yarn build

      - name: ğŸš¢ Deploy preview
        uses: rossjrw/pr-preview-action@v1.2
        with:
          source-dir: ./dist/
